### ISSUE TITLE
Allow streaming as an opt-in when generating large files

### ISSUE THREAD

**Issue by i-arindam** [westonganger/spreadsheet_architect#13]
Since Rails has supported streaming since 3.x, it would be valuable in real world use cases if the file being created is too large. Say, an export of **all the users**.

[Starting example](https://www.sitepoint.com/streaming-with-rails-4/)

**Comment by westonganger** [comment]
I dont know that this would apply to this library. That feature appears is related to streaming the view.

In this case there is no view, I am sending a file to the user. I already use `send_data` which I believe uses data streaming under the hood.
