### ISSUE TITLE
Axlsx deprecation warning

### ISSUE THREAD

**Issue by Loschcode** [westonganger/spreadsheet_architect#22]
Hi, great gem but I recently faced warnings such as

```
/Users/loschcode/.rvm/gems/ruby-2.5.1/gems/axlsx-2.0.1/lib/axlsx/util/validators.rb:96: warning: constant ::Fixnum is deprecated
```

Which seem to be related to your own dependencies. How do you get rid of it ? Is there already a plan to fix that warning ?

**Comment by westonganger** [comment]
This problem is with `axlsx` being poorly maintained, they have not properly released a new version in a long time. This deprecation is fixed in the git master of axlsx. However, a gemspec cannot point to a git dependency so I cannot fix it from my end. Instead add this to your gemfile

```ruby
gem 'axlsx', git: 'https://github.com/randym/axlsx.git'
gem 'spreadsheet_architect'
```

**Comment by Loschcode** [comment]
Thank you very much for the fast answer and quickfix ; it's not ideal but it should do it for now. However, have you thought of changing it to something else ? Could be worth digging I guess 🤔

**Comment by westonganger** [comment]
No `axlsx` is the Ruby defacto standard (although poorly maintained) and I have poured many hours into making this software stable and with many customization options. Theres no way to switch from this without changing and/or losing features.

What you could do, is attempt to press on the `axlsx` maintainers to release a new official version of their library.
