### ISSUE TITLE
Argument column_widths does not seem to work

### ISSUE THREAD

**Issue by Loschcode** [westonganger/spreadsheet_architect#23]
I'm using your library to export XLSX, CSV and ODS. The code is as such

```
      def data
        SpreadsheetArchitect.to_xlsx(arguments)
      end

      def arguments
        {
          sheet_name: spreadsheet.name,
          column_widths: spreadsheet.column_widths,
          headers: spreadsheet.headers,
          data: spreadsheet.data
        }
      end
```

We have `column_widths` with let's say `[10, 10]` and `headers` with `['Set 1', 'Set 2']` which should set the size of each column to `10` and work clean.

It does not work, for some reason my columns end up being all in different sizes, as you can see in the screenshot. Am I missing something with the `column_widths` option or is it bug ?

Here's a screenshot with real data I tried to export a XLSX.

<img width="852" alt="screenshot 2018-08-13 14 26 55" src="https://user-images.githubusercontent.com/6666570/44031791-6dde59f8-9f05-11e8-8e2b-d12cf0b58387.png">

**Comment by westonganger** [comment]
I believe I have located the issue. Can you please test the `fix_custom_column_widths` branch and let me know if that fixes your issue.

**Comment by Loschcode** [comment]
Hi,

It works like a charm with your branch 👍

**Comment by westonganger** [comment]
Beauty! Merged to master. Will be included in v3.1.0, will try to get this release out in the next week or two.

**Comment by westonganger** [comment]
v3.1.0 is now released which contains this fix.

**Comment by MadBomber** [comment]
The release 4.0.0 does not have a working column_widths in my environment.  I will be doing some detailed testing to find problem.  Suspect an old version of axlsx gem.
