### ISSUE TITLE
Unable to use my own spreadsheet_column method

### ISSUE THREAD

**Issue by MattCrl** [westonganger/spreadsheet_architect#27]
For some reason, I'm trying to use my own spreadsheet_column method, like that :
`@dossiers_xlsx = @dossiers.to_xlsx(spreadsheet_columns: :information_list_export)`
But got this error : 
> NoMethodError (undefined method `each_with_index' for :information_list_export:Symbol)

The only way I made it work was by doing a Class method :
```
def self.information_list_export
    column contents here
end
```
Then :
`@dossiers_xlsx = @dossiers.to_xlsx(spreadsheet_columns: Dossier.information_list_export)`
But it doesn't work like I need, the self method doesn't allow me to do what I want. 
Am I missing something ? I'm actually on a project with the 2.0.0 version of spreadsheet-architect.
**(Have to say it works perfectly when I don't overwrite the spreadsheet_column method, but here I need to)**
If anyone can help me, thanks a lot !

**Comment by westonganger** [comment]
Ok so the following needs to be implemented.

We need to add:
- Optional `:spreadsheet_columns_method` argument
- Class wide defaults `:spreadsheet_columns_method` option
- Project wide defaults `:spreadsheet_columns_method` option

**Comment by westonganger** [comment]
In the meantime I would simply drop down to using the SpreadsheetArchitect module directly. Example:

```ruby
headers = ['Name', 'Contents', 'Created At']

data = []
@dossiers.each do |x|
  data << [x.name, x.contents, x.created_at]
end

SpreadsheetArchitect.to_xlsx(headers: headers, data: data)
```

**Comment by westonganger** [comment]
Also with the class method this would work, you just need to wrap the method contents in a Proc.

```ruby
def self.information_list_export
  Proc.new{|x|
    [
      [x.name]
    ]    
column contents here
  }
end

@dossiers_xlsx = @dossiers.to_xlsx(spreadsheet_columns: Dossier.information_list_export)
```

**Comment by westonganger** [comment]
This feature was added in v3.1.0. Please upgrade.
