### ISSUE TITLE
Support caxlsx gem

### ISSUE THREAD

**Issue by westonganger** [westonganger/spreadsheet_architect#28]
A new gem `caxlsx` (Community Axlsx) has been released, Spreadsheet Architect should support this.

**Comment by westonganger** [comment]
Pending resolution to https://github.com/caxlsx/caxlsx/issues/31

**Comment by arambert** [comment]
any news on this?

**Comment by westonganger** [comment]
@arambert was kind of just waiting to examine `caxlsx` development. Seems to be stable. Maybe I will find some time next week to try and implement this. It will have to be a new major version release. I would also like to try to add xlsx freeze functionality (#25) for this release as well.

**Comment by westonganger** [comment]
`caxlsx` integration has now been implemented in master. Please test and let me know how it works out for you.

**Comment by westonganger** [comment]
We are pretty much ready to cut a new release. I would like to see the outcome of https://github.com/caxlsx/caxlsx/pull/44 first though.

**Comment by westonganger** [comment]
SpreadsheetArchitect is now basically ready for the v3.0.0 release. I would just like to let the newly merged caxlsx changes and this libraries new changes to get sit for a couple weeks to see if any issues arise before cutting the release.

**Comment by westonganger** [comment]
v4.0.0 is now released which utilizes `caxlsx`
