### ISSUE TITLE
XLSX_COLUMN_TYPES "already initialized constant" warning

### ISSUE THREAD

**Issue by ug0** [westonganger/spreadsheet_architect#30]
It looks like `XLSX_COLUMN_TYPES` is being defined twice in https://github.com/westonganger/spreadsheet_architect/blob/master/lib/spreadsheet_architect/class_methods/xlsx.rb#L7 and https://github.com/westonganger/spreadsheet_architect/blob/master/lib/spreadsheet_architect.rb#L38

>

**Comment by westonganger** [comment]
v3.3.1 is now released which fixes this.
