### ISSUE TITLE
How to add a value to a specific cell using spreadsheet architecture gem?

### ISSUE THREAD

**Issue by SP8890** [westonganger/spreadsheet_architect#37]
Hi 
I am using below code which is file to add value to first row, 

data = [[1,2,3]]
SpreadsheetArchitect.to_ods(headers: headers, data: data)

but what if I want to add a single value at specific cell? 

ex: cell(2,4) = "8" 

Is there any way to perfom this? 
Please advise. 

Thanks

**Comment by westonganger** [comment]
No this is not possible. The libraries used within this project are write-only libraries (rodf and caxlsx). They are not for reading spreadsheets. As such there will not be any methods to change pre-existing content.

If you want to create a spreadsheet with your single cell value, you would have to add any empty rows and empty cells as required.

**Comment by SP8890** [comment]
spreadsheet is there, I've a task to amend the cell value in ODS file. 
by the way, Thanks for your reply.
