### ISSUE TITLE
I'm running out of memory ....

### ISSUE THREAD

**Issue by MadBomber** [westonganger/spreadsheet_architect#41]
Happy 2022!

My sidekiq workers are running out of memory because I did not anticipate the size of the data arrays I'm using and the number of sheets being generated.

In using the `to_xlsx` method. I am passing the full data array which can be extremely large.  What is being returned is a large object which I am writing to an external file.

I'm NOT  sure that I can do what I want to do ...
1) init the spreadsheet, styles headers etc.
2) pass one data row at a time into to_xlsx
3) update the external file goto 2 until no more data  --  yes I said GOTO :)
4) close the external file.

If I can do something like that, then it should significantly reduce the amount of process memory needed to generate the xlsx file.

I'm not very hopefully.  I will take a look at the internals of axlsx to see if there is anything there that might help.

Any suggestions?

**Comment by MadBomber** [comment]
This was a silly idea.

**Comment by JohnnyHandy** [comment]
How did you solve that?
