### ISSUE TITLE
cool concept

### ISSUE THREAD

**Issue by markmcdonald51** [westonganger/spreadsheet_architect#5]
Great idea to make these functions all available in a single package.

I just tried to use this but got a few errors.

here is what I used:

 f = [["Record ID", :record_id],
 ["Protocol #", :protocol_id],
 ["PI", :pi_name],
 ["Title", :title],
 ["Current Enrollment/Target Enrollment", :ce_te],
 ["Current Enrollment", :ce],
 ["Target Enrollment", :te],
 ["IRB", :irb],
 ["Status", :status],
 ["IRB Termination date", :irb_termination_date],
 ["Date of Last Continuing Review IRB Approval", :date_last_irb_approval],
 ["Date Contiuing Review (expires)", :date_review_expires],
 ["Date of Most Recently Approved Protocol", :date_last_appr_prot],
 ["Version Number of Most Recently Approved Protocol", :version_last_apprv_prot],
 ["Date of Last DSMC Review", :date_last_dsmc_review],
 ["Date of Last Monitoring Visit", :date_last_monitoring_visit],
 ["Type of Last Monitoring Visit", :type_last_monitoring_visit],
 ["CMP/Complexity", :cmp_complexity],
 ["Next IMV", :next_imv],
 ["Comments", :comments]]

Org::Org1::IntramuralStudyOversightAndStatuses1.to_xlsx(sheet_name: 'test', spreadsheet_columns: f)

NoMethodError: undefined method `each_with_index' for #<Org::Org1::IntramuralStudyOversightAndStatuses1:0x007f5e88678340>
from /home/mark/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activemodel-4.2.6/lib/active_model/attribute_methods.rb:433:in `method_missing'

I tried this using to_csv and got the same undefined method `each_with_index'.

Any ideas?

This gem is actually what I am looking for right now. Kudos!

-mark

**Comment by westonganger** [comment]
I broke this in v1.2.4 and fixed this in v1.2.5 which I just released. So just update the gem and it should work correctly.

**Comment by markmcdonald51** [comment]
Awesome! Going to check this out right now --Thanks ;)
