### ISSUE TITLE
ArgumentError using .to_ods method

### ISSUE THREAD

**Issue by JCBlondel** [westonganger/spreadsheet_architect#8]
Hello, first of all thank you for this amazing gem, I will refer to it for every single project. Each time there is a need of "big export", and manual CSV writer methods become a technical debt after some iterations.

I opened an issue because I can use .to_csv and .to_xlsx without any problem, but .to_ods bring me this error:

"ArgumentError: wrong number of arguments (given 1, expected 0)"
"from ....rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spreadsheet_architect-1.4.6/lib/spreadsheet_architect.rb:206:in `to_rodf_spreadsheet'"
"from .....rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spreadsheet_architect-1.4.6/lib/spreadsheet_architect.rb:266:in `to_ods'
	from (irb):1"

I tried every steps from ruby console, watched the miniTest for .to_ods method from the gem, but I cannot get out the ArgumentError. My ruby version is 2.3.1.
Thanks for your help, and congratz for this gem 👍

**Comment by westonganger** [comment]
Ah I see its missing the arguments in a method definition. I just fixed this and release v1.4.7 which fixes this. 

Please note I have made major changes to the `develop` branch which will be v2 of this plugin which already has this fixed.  I hope to release this new version once it has been better tested.

**Comment by JCBlondel** [comment]
Thanks for the fix, it's working!
I had to change my decorator to convert integer and boolean values in string, to make them appear in .ods file generated (each value of this type was not written), but for me it's okay.
Again, thank you for this gem 👍

**Comment by westonganger** [comment]
Yes changes are required for types in the ODS library, RODF. I am in charge of that library. A new release of RODF will correspond with the v2 release of Spreadsheet Architect.
