### ISSUE TITLE
Issue following rodf gem upgrade

### ISSUE THREAD

**Issue by fcarrega** [westonganger/spreadsheet_architect#9]
The `rodf` gem has been updated recently to version 1.0.0.

Spreadsheet Architect has a runtime dependency to this gem, but seems incompatible with the latest version of `rodf`.

The following message is thrown after gems update and environment loading :  `LoadError: cannot load such file -- odf/spreadsheet`

For the moment, the workaround we have implemented is just a fix in our `Gemfile` :

```ruby
gem "rodf", "~> 0.3.7"
```

**Comment by westonganger** [comment]
Thanks for pointing this out

v1.4.8 just released which fixes this. 

v2.0.0 of `spreadsheet_architect` coming soon with compatibility with latest version of `rodf`.

**Comment by fcarrega** [comment]
Works perfectly, thank you !
